# Generated by Django 4.0.4 on 2022-06-20 20:55

from django.db import migrations, models
import os

def create_CongigRow(apps, schema_editor):
    Congif = apps.get_model('techdes', 'Config')
    MainDir = os.getcwd()

    Congif.objects.create(
        datafiles='', applications=''
        , output=os.path.join(MainDir, 'output')
        , date_format='%Y%m%d%H%M%S'
        , output_encoding='utf-8', input_encoding='cp1251'
        , contents=os.path.join(MainDir, 'contents')
        , dbpattern='(?<=DB\(\')[0-9а-яА-Я_\sa-zA-Z]+'
        , empty_value='-'
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafiles', models.CharField(max_length=200)),
                ('applications', models.CharField(max_length=200)),
                ('output', models.CharField(max_length=200)),
                ('date_format', models.CharField(max_length=30)),
                ('output_encoding', models.CharField(max_length=10)),
                ('input_encoding', models.CharField(max_length=10)),
                ('contents', models.CharField(max_length=200)),
                ('dbpattern', models.CharField(max_length=50)),
                ('empty_value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('action', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RunPython(create_CongigRow),
    ]
